version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  nginx-metric-exporter:
    container_name: nginx-metric-expoter
    image: nginx/nginx-prometheus-exporter
    ports:
      - 9113:9113
    command: -nginx.scrape-uri http://192.168.10.102:80/metrics
  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana:9.0.5
    ports:
      - 3000:3000
