global:
  scrape_interval: "10s"
  external_labels:
    monitor: "local-monitor"

scrape_configs:
  - job_name: "nginx-exporter"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "nginx-metric-exporter:9113"
